prompt --application/deployment/install/install_flex_registry_table_and_trigger
begin
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(14876068604952650937)
,p_install_id=>wwv_flow_api.id(17817343456864234187)
,p_name=>'Flex Registry Table and Trigger'
,p_sequence=>470
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'create table eba_cust_flex_registry (',
'    id                         number primary key,',
'    row_version_number         integer,',
'    row_key                    varchar2(255),',
'    flexible_table             varchar2(128) not null,',
'    flexible_column            varchar2(128) not null,',
'    friendly_name              varchar2(128) ,',
'    assigned_yn                varchar2(1)   not null,',
'    active_yn                  varchar2(1)   not null,',
'    --',
'    form_label_text            varchar2(255) not null,',
'    report_label_text          varchar2(255),',
'    is_required_yn             varchar2(1)   not null,',
'    is_displayed_on_ir         varchar2(1)   not null,',
'    label_template_id          number        not null,',
'    display_as                 varchar2(255) not null,',
'                               constraint eba_cust_flex_chk_dsply_as_val check (display_as in (''SELECT_LIST'',''TEXT'',''TEXTAREA'',''DATE'',''NUMBER'')),',
'    width                      number        not null,',
'    max_width                  number        not null,',
'    height                     number        not null,',
'    format_mask                varchar2(30),',
'    label_alignment            varchar2(30),',
'    help_text                  varchar2(4000),',
'    lov_type                   varchar2(30),',
'    lov_sql_query              clob,',
'    lov_display_col            varchar2(30),',
'    lov_return_col             varchar2(30),',
'    default_value              varchar2(4000),',
'    rpt_hdr_alignment          varchar2(30),',
'    condition_type             varchar2(255),',
'    condition1                 varchar2(4000),',
'    condition2                 varchar2(4000),',
'    --',
'    created_by                 varchar2(255),',
'    created                    timestamp with local time zone,',
'    updated_by                 varchar2(255),',
'    updated                    timestamp with local time zone',
');',
'',
'create or replace trigger eba_cust_flex_registry_biu',
'    before insert or update on eba_cust_flex_registry',
'    for each row',
'begin',
'    if inserting and :new.id is null then',
'        :new.id := eba_cust.gen_id();',
'    end if;',
'    if inserting and :new.row_key is null then',
'        declare',
'            l_next_seq_val number;',
'        begin',
'           select eba_cust_seq.nextval into l_next_seq_val from dual;',
'           :new.row_key := eba_cust_fw.compress_int(l_next_seq_val);',
'        end;',
'    end if;',
'    if inserting then',
'        :new.row_version_number := 1;',
'        :new.created_by := nvl(wwv_flow.g_user,user);',
'        :new.created := localtimestamp;',
'    end if;',
'    if updating then',
'        :new.row_version_number := nvl(:old.row_version_number,1) + 1;',
'    end if;',
'    :new.updated_by := nvl(wwv_flow.g_user,user);',
'    :new.updated := localtimestamp;',
'end eba_cust_flex_registry_biu;',
'/',
'show errors',
'',
'alter trigger eba_cust_flex_registry_biu enable;'))
);
end;
/
