prompt --application/deployment/install/install_populate_flex_registry
begin
wwv_flow_api.create_install_script(
 p_id=>wwv_flow_api.id(14880216708546711099)
,p_install_id=>wwv_flow_api.id(17817343456864234187)
,p_name=>'Populate flex registry'
,p_sequence=>520
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'declare',
'    type postfixes_t is table of varchar2(30);',
'    l_postfixes postfixes_t := postfixes_t(',
'                          ''01'',''02'',''03'',''04'',',
'                          ''05'',''06'',''07'',''08'',',
'                          ''N01'',''N02'',''N03'',''N04'',',
'                          ''D01'',''D02'',''D03'',''D04'',',
'                          ''CLOB'');',
'',
'    type table_r is record (',
'        table_name        varchar2(30)',
'    );',
'    type tables_t is table of table_r index by varchar2(30);',
'    l_tables tables_t;',
'',
'    l_tbl varchar2(30);',
'begin',
'    l_tables(''CUSTOMER'').table_name := ''EBA_CUST_CUSTOMERS'';',
'    --',
'    l_tables(''CONTACT'').table_name  := ''EBA_CUST_CONTACTS'';',
'    --',
'    l_tables(''PRODUCT'').table_name  := ''EBA_CUST_PRODUCTS'';',
'    -- TODO: Add other tables here as necessary.',
'',
'    l_tbl := l_tables.FIRST;',
'    while l_tbl is not null loop',
'        for pf in 1..l_postfixes.COUNT loop',
'            insert into eba_cust_flex_registry (',
'                flexible_table,',
'                flexible_column,',
'                active_yn,',
'                form_label_text,',
'                is_required_yn,',
'                --',
'                label_template_id,',
'                display_as,',
'                width,',
'                max_width,',
'                height,',
'                is_displayed_on_ir,',
'                assigned_yn,',
'                --',
'                condition_type,',
'                condition1,',
'                condition2',
'            )',
'            values (',
'                l_tables(l_tbl).table_name,',
'                l_tbl||''_FLEX_''||l_postfixes(pf),',
'                ''N'',',
'                l_tbl||''_FLEX_''||l_postfixes(pf),',
'                ''N'',',
'                --',
'                0,',
'                case when l_postfixes(pf) = ''CLOB''',
'                    then ''TEXTAREA''',
'                    else ''TEXT''',
'                end,',
'                case when l_postfixes(pf) = ''CLOB''',
'                    then 80',
'                    else 30',
'                end,',
'                case when l_postfixes(pf) = ''CLOB''',
'                    then 30000',
'                    else 4000',
'                end,',
'                case when l_postfixes(pf) = ''CLOB''',
'                    then 5',
'                    else 1',
'                end,',
'                ''N'',',
'                ''N'',',
'                --',
'                ''EXISTS'',',
'                ''select null from eba_cust_flex_registry ''',
'                    ||''where flexible_table = ''''''',
'                    ||l_tables(l_tbl).table_name',
'                    ||'''''' and flexible_column = ''''''',
'                    ||l_tbl||''_FLEX_''||l_postfixes(pf)',
'                    ||'''''' and active_yn = ''''Y''''''',
'                    ||'' and assigned_yn = ''''Y'''''',',
'                null',
'            );',
'        end loop;',
'        l_tbl := l_tables.NEXT( l_tbl );',
'    end loop;',
'end;',
'/',
'show errors',
'',
'commit;',
''))
);
end;
/
